// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfoM1mkpULUxqCw7GiP1UM0LNTbRGA3cQ',
    appId: '1:927029234587:web:9d85c4ea1678de1d1d2f3e',
    messagingSenderId: '927029234587',
    projectId: 'rideshare-4e972',
    authDomain: 'rideshare-4e972.firebaseapp.com',
    storageBucket: 'rideshare-4e972.firebasestorage.app',
    measurementId: 'G-DCHQX9DBMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSFjJ6cw7PojX-KeaiUfW7iTi2HCBU34',
    appId: '1:927029234587:android:345fbbd40930c0631d2f3e',
    messagingSenderId: '927029234587',
    projectId: 'rideshare-4e972',
    storageBucket: 'rideshare-4e972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBQ22DtQ5kCv4EJtLdhAbPZaYYcY-0bA',
    appId: '1:927029234587:ios:f31fdfe23800e55b1d2f3e',
    messagingSenderId: '927029234587',
    projectId: 'rideshare-4e972',
    storageBucket: 'rideshare-4e972.firebasestorage.app',
    iosBundleId: 'com.example.rideShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyBQ22DtQ5kCv4EJtLdhAbPZaYYcY-0bA',
    appId: '1:927029234587:ios:f31fdfe23800e55b1d2f3e',
    messagingSenderId: '927029234587',
    projectId: 'rideshare-4e972',
    storageBucket: 'rideshare-4e972.firebasestorage.app',
    iosBundleId: 'com.example.rideShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfoM1mkpULUxqCw7GiP1UM0LNTbRGA3cQ',
    appId: '1:927029234587:web:00d29bbc0caaf0c01d2f3e',
    messagingSenderId: '927029234587',
    projectId: 'rideshare-4e972',
    authDomain: 'rideshare-4e972.firebaseapp.com',
    storageBucket: 'rideshare-4e972.firebasestorage.app',
    measurementId: 'G-JS51Y44JDX',
  );
}
